### ISSUE TITLE
Поддержка addr:suburb в адресах

### ISSUE THREAD

**Issue by DinamikGitHub** [Zkir/osm2dcm#42]
Необходимо добавить поддержку addr:suburb.
Если на улице есть name=Название + addr:suburb=Район, на доме есть addr:housenumber=1 и:
а) addr:street=Название + addr:suburb=Район или
б) дом (точечный, полигональный или мультиполигональный) включён в отношение street addr:street=Название + addr:suburb=Район ,
поиском должен находиться дом по адресу "Название, дом 1" в Районе.

**Comment by Zkir** [comment]
Добавил, во всяком случае для тегов. Не очень уверен на счет отношений.
