### ISSUE TITLE
POI, содержащие в названии точку

### ISSUE THREAD

**Issue by DinamikGitHub** [Zkir/osm2dcm#79]
Необходимо нормализовать поиск POI, содержащих в названии точку. Один из возможных вариантов решения проблемы - заменять при конвертации точку на пробел.

См. http://forum.openstreetmap.org/viewtopic.php?pid=330082#p330082

**Comment by Zkir** [comment]
Это надо в ситигидовский суппорт писать. Или прямо на гугл-маркет)
